[project]
name = "healthflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "dotenv>=0.9.9",
    "langchain>=0.3.27",
    "langchain-core>=0.3.76",
    "langchain-deepseek>=0.1.4",
    "langchain-mcp-adapters>=0.1.9",
    "langgraph>=0.6.7",
    "loguru>=0.7.3",
    "nest-asyncio>=1.6.0",
    "openai>=1.108.0",
    "pydantic>=2.11.9",
    "rich>=14.1.0",
    "tenacity>=9.1.2",
    "toml>=0.10.2",
    "tooluniverse>=0.2.0",
    "typer>=0.17.4",
]
